#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond" indefinitely.
# Add a sleep 2 at each iteration of the loop.
for ((i=1; i; i++)); do
        echo "To infinity and beyond"
        sleep 2
done
