#!/usr/bin/env bash
# This is a  Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
count=0
while [ $count -lt 10 ]; do
	if [ $count -eq 9 ]; then
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
